name: Publish site

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup ruby & install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    - name: Build production jekyll site
      run: JEKYLL_ENV=production NODE_ENV=production bundle exec jekyll build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
